name: TradingView to Telegram

on:
  workflow_dispatch:
  repository_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  send_signal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Signal to Telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ env.TELEGRAM_CHAT_ID }}&text=Signal from TradingView: New issue or pull request detected"
